// <auto-generated />
namespace MyBills.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class BillTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BillTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202112211414221_BillTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
